### ISSUE TITLE
issues running with test dataset

### ISSUE THREAD

**Issue by LennWhy** [aomlomics/tourmaline#82]
Hi,
 
I've installed the tourmaline git directory to see tourmaline would run smoothly with the test data on my HPC (Linux), but somehow errors are showing up when I run `snakemake dada2_pe_denoise`. Please see below.

```
R version 4.0.2 (2020-06-22) 
Loading required package: Rcpp
DADA2: 1.18.0 / Rcpp: 1.0.10 / RcppParallel: 5.1.6 
1) Filtering Error in validObject(.Object) : 
  invalid class “SRFilterResult” object: superclass "Mnumeric" not defined in the environment of the object's class
Execution halted
Traceback (most recent call last):
  File "/miniconda/yes/envs/qiime2-2021.2/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 264, in denoise_paired
    run_commands([cmd])
  File "/miniconda/yes/envs/qiime2-2021.2/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 36, in run_commands
    subprocess.run(cmd, check=True)
  File "/miniconda/yes/envs/qiime2-2021.2/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['run_dada_paired.R', '/tmp/tmpn1wfffzw/forward', '/tmp/tmpn1wfffzw/reverse', '/tmp/tmpn1wfffzw/output.tsv.biom', '/tmp/tmpn1wfffzw/track.tsv', '/tmp/tmpn1wfffzw/filt_f', '/tmp/tmpn1wfffzw/filt_r', '240', '190', '0', '0', '2.0', '2.0', '2', 'independent', 'consensus', '1.0', '1', '1000000']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "miniconda/yes/envs/qiime2-2021.2/lib/python3.6/site-packages/q2cli/commands.py", line 329, in __call__
    results = action(**arguments)
  File "<decorator-gen-522>", line 2, in denoise_paired
  File "/miniconda/yes/envs/qiime2-2021.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/miniconda/yes/envs/qiime2-2021.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/miniconda/yes/envs/qiime2-2021.2/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 279, in denoise_paired
    " and stderr to learn more." % e.returncode)
Exception: An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.

Plugin error from dada2:

  An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.

See above for debug info.
Error in job denoise_dada2_pe while creating output files 02-output-dada2-pe-unfiltered/00-table-repseqs/table.qza, 02-output-dada2-pe-unfiltered/00-table-repseqs/repseqs.qza, 02-output-dada2-pe-unfiltered/00-table-repseqs/dada2_stats.qza.
RuleException:
CalledProcessError in line 549 of /tourmaline/Snakefile:
Command 'qiime dada2 denoise-paired --i-demultiplexed-seqs 01-imported/fastq_pe.qza --p-trunc-len-f 240 --p-trunc-len-r 190 --p-trim-left-f 0 --p-trim-left-r 0 --p-max-ee-f 2 --p-max-ee-r 2 --p-trunc-q 2 --p-pooling-method independent --p-chimera-method consensus --p-min-fold-parent-over-abundance 1 --p-n-reads-learn 1000000 --p-n-threads 1 --p-hashed-feature-ids --o-table 02-output-dada2-pe-unfiltered/00-table-repseqs/table.qza --o-representative-sequences 02-output-dada2-pe-unfiltered/00-table-repseqs/repseqs.qza --o-denoising-stats 02-output-dada2-pe-unfiltered/00-table-repseqs/dada2_stats.qza --verbose' returned non-zero exit status 1.
  File "/tourmaline/Snakefile", line 549, in __rule_denoise_dada2_pe
  File "/miniconda/yes/envs/qiime2-2021.2/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message

```

Can you please advise?

Thanks

**Comment by ksilnoaa** [comment]
It's likely the issue was with a version of the R Matrix package that was updated beyond the qiime2 .yml file:
https://github.com/benjjneb/dada2/issues/1378

**Comment by ksilnoaa** [comment]
It's likely the issue was with a version of the R Matrix package that was updated beyond the qiime2 .yml file:
https://github.com/benjjneb/dada2/issues/1378
